networks:
  my-net:

volumes:
  caddy:

services:
  node:
    container_name: logging-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-net
    ports:
      - '9000:3000'
    tty: true
